id: opecha:P005575
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5907
  title: མཁའ་སྤྱོད་འབྲས་མོ་ལྗོངས་ཀྱི་གཙུག་ནོར་སྤྲུལ་པའི་རྣལ་འབྱོར་མཆེད་བཞི་བརྒྱུད་འཛིན་དང་བཅས་པའི་བྱུང་བ་བརྗོད་པ་བློ་གསར་གཞོན་ནུའི་དགའ་སྟོན་
  volume: ''
  author: ''
